# For full config options, check the docs:
#    docs.serverless.com
#

service: product-service-6
frameworkVersion: '3'

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  httpApi:
    cors: true
  environment:
    PG_HOST: ${env:PG_HOST}
    PG_PORT: ${env:PG_PORT}
    PG_DATABASE: ${env:PG_DATABASE}
    PG_USERNAME: ${env:PG_USERNAME}
    PG_PASSWORD: ${env:PG_PASSWORD}

custom:
  sqsQueueName: ab-shop-products-queue
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'npm'
    excludeFiles: /**/*.test.js

package:
  individually: true

functions:
  getProducts:
    handler: handlers/getProductsList.getProductsList
    events:
      - httpApi:
          path: /products
          method: get
  createProduct:
    handler: handlers/createProduct.createProduct
    events:
      - httpApi:
          path: /products
          method: post
  getProductById:
    handler: handlers/getProductsById.getProductsById
    events:
      - httpApi:
          path: /products/{productId}
          method: get
  catalogBatchProcess:
    handler: handlers/catalogBatchProcess.catalogBatchProcess
    events:
      - sqs:
          batchSize: 5
          arn:
            - "${cf:ab-shop-import-service-${self:provider.stage}.SQSQueueArn}"

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
